version: '3.7'

services:
  samba:
    build: .
    container_name: samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - samba_data:/srv/samba/shared
    restart: always

volumes:
  samba_data:
