# # Use admin/pass as user/password credentials to login to openemr (from OE_USER and OE_PASS below)
# # MYSQL_HOST and MYSQL_ROOT_PASS are required for openemr
# # MYSQL_USER, MYSQL_PASS, OE_USER, MYSQL_PASS are optional for openemr and
# #   if not provided, then default to openemr, openemr, admin, and pass respectively.
version: '3.1'
services:
  mysql:
    restart: always
    image: mariadb:10.11
    command: ['mysqld','--character-set-server=utf8mb4']
    volumes:
    - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr:
    restart: always
    image: smehdilaraib/oe:v1
    ports:
    - 80:80
    - 443:443
    volumes:
    - logvolume01:/var/log
    - sitevolume:/var/www/localhost/htdocs/openemr/sites
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      MYSQL_PASS: openemr
      OE_USER: admin
      OE_PASS: pass
     
    depends_on:
    - mysql
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
        - LDAP_ORGANISATION=exampleorg
        - LDAP_DOMAIN=example.in
        - "LDAP_BASE_DN=dc=example,dc=in"
        - LDAP_ADMIN_PASSWORD=password
    ports:
        - 389:389
        - 636:636
  # samba:
  #   image: dperson/samba
  #   environment:
  #     TZ: 'EST5EDT'
  #   ports:
  #     - "137:137/udp"
  #     - "138:138/udp"
  #     - "139:139/tcp"
  #     - "9445:445/tcp"
  #   restart: unless-stopped
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - sitevolume:/var/samba/shared/openemr/sites
  #   command: >
  #     -s "OpenEMR;/var/samba/shared/openemr/sites;yes;no;no;admin"
  #     -u "admin;pass"
  #     -p

  # elasticsearch:
  #   image: elasticsearch:7.16.2
  #   container_name: elasticsearch
  #   restart: always
  #   volumes:
  #     - elastic_data:/usr/share/elasticsearch/data/
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  #     discovery.type: single-node    
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #   networks:
  #     - elk

  # logstash:
  #   image: logstash:7.16.2
  #   container_name: logstash
  #   restart: always
  #   volumes:
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline
  #     - logvolume01:/var/log/openemr
  #   command: logstash -f /usr/share/logstash/pipeline/logstash.conf
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - '9600:9600'
  #     - '5044:5044'  # Added port for Logstash input
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"  
  #   networks:
  #     - elk

  # kibana:
  #   image: kibana:7.16.2
  #   container_name: kibana
  #   restart: always       
  #   ports:
  #     - '5601:5601'
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200  
  #   depends_on:
  #     - elasticsearch  
  #   networks:
  #     - elk
  # tinyproxy:
  #   container_name: tinyproxy
  #   ports:
  #     - '8888:8888'
  #   volumes:
  #     - './tinyproxy.conf:/etc/tinyproxy.conf:ro'
  #   image: 'ajoergensen/tinyproxy:latest'

  # vault:
  #   image: hashicorp/vault:latest
  #   environment:
  #     VAULT_DEV_ROOT_TOKEN_ID: testtoken
  #   ports:
  #     - 8200:8200
  #   privileged: true
  #   volumes:
  #   - vault-data:/var/lib/vault:rw

volumes:
  logvolume01: {}
  sitevolume: {}
  databasevolume: {}
  # vault-data: {}
  # elastic_data: {}

networks:
  elk:
    driver: bridge
# version: '3.1'
# services:
#   mysql:
#     restart: always
#     image: mariadb:10.11
#     command: ['mysqld','--character-set-server=utf8mb4']
#     volumes:
#     - databasevolume:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#   openemr:
#     restart: always
#     image: openemr/openemr:7.0.2
#     ports:
#     - 80:80
#     - 443:443
#     volumes:
#     - logvolume01:/var/log
#     - sitevolume:/var/www/localhost/htdocs/openemr/sites
#     environment:
#       MYSQL_HOST: mysql
#       MYSQL_ROOT_PASS: root
#       MYSQL_USER: openemr
#       MYSQL_PASS: openemr
#       OE_USER: admin
#       OE_PASS: pass
#     depends_on:
#     - mysql
# volumes:
#   logvolume01: {}
#   sitevolume: {}
#   databasevolume: {}