services:
  zeek:
    image: zeekurity/zeek:5.2.2
    container_name: zeek
    volumes:
      - ./zeek/logs:/usr/local/zeek/logs
    networks:
      - elk
    depends_on:
      - logstash

  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk

  logstash:
    image: logstash:7.17.3
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf 
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
      - '5044:5044'  # Added port for Logstash input
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    networks:
      - elk

  kibana:
    image: kibana:7.17.3
    container_name: kibana
    restart: always       
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200  
    depends_on:
      - elasticsearch  
    networks:
      - elk

volumes:
  elastic_data: {}

networks:
  elk:
